# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celllines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celllineorganization',
            name='idcelllineorganization',
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='accesslevel',
            field=models.CharField(max_length=20, verbose_name='Accesslevel', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='aliquotstatus',
            name='aliquotstatus',
            field=models.CharField(max_length=20, verbose_name='Aliquotstatus', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='approveduse',
            name='approveduse',
            field=models.CharField(max_length=60, verbose_name='Approveduse', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='batchstatus',
            name='batchstatus',
            field=models.CharField(max_length=20, verbose_name='Batchstatus', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='binnedage',
            name='binnedage',
            field=models.CharField(max_length=5, verbose_name='Binnedage', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cellline',
            name='biosamplesid',
            field=models.CharField(unique=True, max_length=12, verbose_name='Biosamplesid'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cellline',
            name='celllinecomments',
            field=models.CharField(max_length=1000, verbose_name='Celllinecomments', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cellline',
            name='celllinediseaseaddinfo',
            field=models.CharField(max_length=100, verbose_name='Celllinediseaseaddinfo', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cellline',
            name='celllineecaccurl',
            field=models.CharField(max_length=100, verbose_name='Celllineecaccurl', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cellline',
            name='celllinename',
            field=models.CharField(unique=True, max_length=15, verbose_name='Celllinename'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cellline',
            name='celllinenamesynonyms',
            field=models.CharField(max_length=1000, verbose_name='Celllinenamesynonyms', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cellline',
            name='depositorscelllineuri',
            field=models.CharField(max_length=45, verbose_name='Depositorscelllineuri', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinealiquot',
            name='aliquotstatusdate',
            field=models.CharField(max_length=20, verbose_name='Aliquotstatusdate', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineannotation',
            name='celllineannotation',
            field=models.CharField(max_length=1000, verbose_name='Celllineannotation', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineannotation',
            name='celllineannotationsource',
            field=models.CharField(max_length=45, verbose_name='Celllineannotationsource', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineannotation',
            name='celllineannotationsourceid',
            field=models.CharField(max_length=45, verbose_name='Celllineannotationsourceid', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineannotation',
            name='celllineannotationsourceversion',
            field=models.CharField(max_length=45, verbose_name='Celllineannotationsourceversion', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinebatch',
            name='batchstatusdate',
            field=models.CharField(max_length=20, verbose_name='Batchstatusdate', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecharacterization',
            name='certificateofanalysispassage',
            field=models.CharField(max_length=5, verbose_name='Certificateofanalysispassage', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecharacterization',
            name='hepititusb',
            field=models.IntegerField(null=True, verbose_name='Hepititusb', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecharacterization',
            name='hepititusc',
            field=models.IntegerField(null=True, verbose_name='Hepititusc', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecharacterization',
            name='hiv1screening',
            field=models.IntegerField(null=True, verbose_name='Hiv1screening', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecharacterization',
            name='hiv2screening',
            field=models.IntegerField(null=True, verbose_name='Hiv2screening', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecharacterization',
            name='mycoplasma',
            field=models.IntegerField(null=True, verbose_name='Mycoplasma', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecollection',
            name='celllinecollectiontotal',
            field=models.IntegerField(null=True, verbose_name='Celllinecollectiontotal', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecollection',
            name='celllinecollectionupdatedby',
            field=models.CharField(max_length=45, verbose_name='Celllinecollectionupdatedby', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecollection',
            name='celllinecollectionupdatetype',
            field=models.IntegerField(null=True, verbose_name='Celllinecollectionupdatetype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecomments',
            name='celllinecommentsupdatedby',
            field=models.IntegerField(null=True, verbose_name='Celllinecommentsupdatedby', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecomments',
            name='celllinecommentsupdatedtype',
            field=models.IntegerField(null=True, verbose_name='Celllinecommentsupdatedtype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecomments',
            name='commentscellline',
            field=models.IntegerField(null=True, verbose_name='Commentscellline', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecultureconditions',
            name='co2concentration',
            field=models.IntegerField(null=True, verbose_name='Co2concentration', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecultureconditions',
            name='feedercellid',
            field=models.CharField(max_length=45, verbose_name='Feedercellid', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecultureconditions',
            name='feedercelltype',
            field=models.CharField(max_length=45, verbose_name='Feedercelltype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinecultureconditions',
            name='o2concentration',
            field=models.IntegerField(null=True, verbose_name='O2concentration', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineculturesupplements',
            name='supplement',
            field=models.CharField(max_length=45, verbose_name='Supplement', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineculturesupplements',
            name='supplementamount',
            field=models.CharField(max_length=45, verbose_name='Supplementamount', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinederivation',
            name='availableasclinicalgrade',
            field=models.CharField(max_length=4, verbose_name='Availableasclinicalgrade', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinederivation',
            name='derivedundergmp',
            field=models.CharField(max_length=4, verbose_name='Derivedundergmp', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinederivation',
            name='primarycelltypecellfinderid',
            field=models.CharField(max_length=45, verbose_name='Primarycelltypecellfinderid', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinederivation',
            name='primarycelltypename',
            field=models.CharField(max_length=45, verbose_name='Primarycelltypename', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinederivation',
            name='selectioncriteriaforclones',
            field=models.CharField(max_length=1000, verbose_name='Selectioncriteriaforclones', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinederivation',
            name='xenofreeconditions',
            field=models.CharField(max_length=4, verbose_name='Xenofreeconditions', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinediffpotency',
            name='passagenumber',
            field=models.CharField(max_length=5, verbose_name='Passagenumber', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinediffpotencymolecule',
            name='celllinediffpotencymarker',
            field=models.IntegerField(null=True, verbose_name='Celllinediffpotencymarker', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinegenemutations',
            name='weblink',
            field=models.CharField(max_length=100, verbose_name='Weblink', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinegeneticmod',
            name='celllinegeneticmod',
            field=models.CharField(max_length=45, verbose_name='Celllinegeneticmod', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinegenomeseq',
            name='celllinegenomeseqlink',
            field=models.CharField(max_length=45, verbose_name='Celllinegenomeseqlink', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinegenotypingother',
            name='celllinegenotypingother',
            field=models.CharField(max_length=1000, verbose_name='Celllinegenotypingother', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinehlatyping',
            name='celllinehlaallele1',
            field=models.CharField(max_length=45, verbose_name='Celllinehlaallele1', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinehlatyping',
            name='celllinehlaallele2',
            field=models.CharField(max_length=45, verbose_name='Celllinehlaallele2', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinehlatyping',
            name='celllinehlaclass',
            field=models.IntegerField(null=True, verbose_name='Celllinehlaclass', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinekaryotype',
            name='karyotype',
            field=models.CharField(max_length=45, verbose_name='Karyotype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinekaryotype',
            name='passagenumber',
            field=models.CharField(max_length=5, verbose_name='Passagenumber', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelab',
            name='clonenumber',
            field=models.IntegerField(null=True, verbose_name='Clonenumber', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelab',
            name='culturesystemcomment',
            field=models.CharField(max_length=45, verbose_name='Culturesystemcomment', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelab',
            name='expansioninprogress',
            field=models.IntegerField(null=True, verbose_name='Expansioninprogress', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelab',
            name='funder',
            field=models.CharField(max_length=45, verbose_name='Funder', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelab',
            name='passagenumber',
            field=models.CharField(max_length=5, verbose_name='Passagenumber', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q10managedaccess',
            field=models.CharField(max_length=1000, verbose_name='Q10managedaccess', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q1donorconsent',
            field=models.IntegerField(null=True, verbose_name='Q1donorconsent', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q2donortrace',
            field=models.IntegerField(null=True, verbose_name='Q2donortrace', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q3irbapproval',
            field=models.IntegerField(null=True, verbose_name='Q3irbapproval', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q5informedconsentreference',
            field=models.CharField(max_length=20, verbose_name='Q5informedconsentreference', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q6restrictions',
            field=models.CharField(max_length=1000, verbose_name='Q6restrictions', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q7iprestrictions',
            field=models.CharField(max_length=1000, verbose_name='Q7iprestrictions', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinelegal',
            name='q9applicablelegislationandregulation',
            field=models.CharField(max_length=1000, verbose_name='Q9applicablelegislationandregulation', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineorganization',
            name='orgstatus',
            field=models.IntegerField(null=True, verbose_name='Orgstatus', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllineorgtype',
            name='celllineorgtype',
            field=models.CharField(max_length=45, verbose_name='Celllineorgtype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinepublication',
            name='celllinepublicationdoiurl',
            field=models.CharField(max_length=1000, verbose_name='Celllinepublicationdoiurl', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinepublication',
            name='pubmedreference',
            field=models.CharField(max_length=45, verbose_name='Pubmedreference', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinesnp',
            name='weblink',
            field=models.CharField(max_length=45, verbose_name='Weblink', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinesnpdetails',
            name='celllinesnpchromosomalposition',
            field=models.CharField(max_length=45, verbose_name='Celllinesnpchromosomalposition', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinesnpdetails',
            name='celllinesnpgene',
            field=models.CharField(max_length=45, verbose_name='Celllinesnpgene', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinesnprslinks',
            name='rslink',
            field=models.CharField(max_length=100, verbose_name='Rslink', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinesnprslinks',
            name='rsnumber',
            field=models.CharField(max_length=45, verbose_name='Rsnumber', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinestatus',
            name='celllinestatus',
            field=models.CharField(max_length=20, verbose_name='Celllinestatus', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinestrfingerprinting',
            name='allele1',
            field=models.CharField(max_length=45, verbose_name='Allele1', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinestrfingerprinting',
            name='allele2',
            field=models.CharField(max_length=45, verbose_name='Allele2', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinevalue',
            name='othervalue',
            field=models.CharField(max_length=100, verbose_name='Othervalue', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinevalue',
            name='potentialuse',
            field=models.CharField(max_length=100, verbose_name='Potentialuse', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinevalue',
            name='valuetoresearch',
            field=models.CharField(max_length=100, verbose_name='Valuetoresearch', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinevalue',
            name='valuetosociety',
            field=models.CharField(max_length=100, verbose_name='Valuetosociety', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celllinevector',
            name='vectorexcisable',
            field=models.CharField(max_length=4, verbose_name='Vectorexcisable', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='celltype',
            name='celltype',
            field=models.CharField(max_length=30, verbose_name='Celltype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clinicaltreatmentb4donation',
            name='clininicaltreatmentb4donation',
            field=models.CharField(max_length=45, verbose_name='Clininicaltreatmentb4donation', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='buildingnumber',
            field=models.CharField(max_length=20, verbose_name='Buildingnumber', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=45, verbose_name='City', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='emailaddress',
            field=models.CharField(max_length=45, verbose_name='Emailaddress', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(max_length=20, verbose_name='Fax', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobilephone',
            field=models.CharField(max_length=20, verbose_name='Mobilephone', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='officephone',
            field=models.CharField(max_length=20, verbose_name='Officephone', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='statecounty',
            field=models.IntegerField(null=True, verbose_name='Statecounty', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=45, verbose_name='Street', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='suiteoraptordept',
            field=models.CharField(max_length=10, verbose_name='Suiteoraptordept', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(max_length=45, verbose_name='Website', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='contacttype',
            field=models.CharField(max_length=45, verbose_name='Contacttype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=45, verbose_name='Country', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='country',
            name='countrycode',
            field=models.CharField(max_length=3, verbose_name='Countrycode'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='culturemedium',
            name='culturemediumbase',
            field=models.CharField(max_length=45, verbose_name='Culturemediumbase', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='culturemedium',
            name='serumconcentration',
            field=models.IntegerField(null=True, verbose_name='Serumconcentration', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='culturesystem',
            name='culturesystem',
            field=models.CharField(max_length=45, verbose_name='Culturesystem', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease',
            field=models.CharField(max_length=45, verbose_name='Disease', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='disease',
            name='icdcode',
            field=models.CharField(unique=True, max_length=10, verbose_name='Icdcode', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='abstract',
            field=models.CharField(max_length=1000, verbose_name='Abstract', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='accesslevel',
            field=models.IntegerField(null=True, verbose_name='Accesslevel', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='authors',
            field=models.CharField(max_length=1000, verbose_name='Authors', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='cellline',
            field=models.IntegerField(null=True, verbose_name='Cellline', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='documentdepositor',
            field=models.IntegerField(null=True, verbose_name='Documentdepositor', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='documentupdate',
            field=models.IntegerField(null=True, verbose_name='Documentupdate', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='documentupdatedby',
            field=models.IntegerField(null=True, verbose_name='Documentupdatedby', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='documentupdatetype',
            field=models.IntegerField(null=True, verbose_name='Documentupdatetype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.IntegerField(null=True, verbose_name='Owner', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=45, verbose_name='Title', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(max_length=5, verbose_name='Version', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='documenttype',
            field=models.CharField(max_length=30, verbose_name='Documenttype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='cellabnormalkaryotype',
            field=models.CharField(max_length=45, verbose_name='Cellabnormalkaryotype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='diseaseadditionalinfo',
            field=models.CharField(max_length=45, verbose_name='Diseaseadditionalinfo', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorabnormalkaryotype',
            field=models.CharField(max_length=45, verbose_name='Donorabnormalkaryotype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='hescregdonorid',
            field=models.CharField(max_length=3, verbose_name='Hescregdonorid', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='otherclinicalinformation',
            field=models.CharField(max_length=100, verbose_name='Otherclinicalinformation', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='providerdonorid',
            field=models.CharField(max_length=45, verbose_name='Providerdonorid', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='enzymatically',
            name='enzymatically',
            field=models.CharField(max_length=45, verbose_name='Enzymatically', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='enzymefree',
            name='enzymefree',
            field=models.CharField(max_length=45, verbose_name='Enzymefree', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Gender', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='germlayer',
            name='germlayer',
            field=models.CharField(max_length=15, verbose_name='Germlayer', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hla',
            name='hla',
            field=models.CharField(max_length=45, verbose_name='Hla', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='karyotypemethod',
            name='karyotypemethod',
            field=models.CharField(max_length=45, verbose_name='Karyotypemethod', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=45, verbose_name='Keyword', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lastupdatetype',
            name='lastupdatetype',
            field=models.CharField(max_length=45, verbose_name='Lastupdatetype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='marker',
            name='marker',
            field=models.CharField(max_length=20, verbose_name='Marker', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='molecule',
            name='moleculename',
            field=models.CharField(max_length=45, verbose_name='Moleculename', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='molecule',
            name='referencesource',
            field=models.CharField(max_length=45, verbose_name='Referencesource', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='molecule',
            name='referencesourceid',
            field=models.CharField(max_length=45, verbose_name='Referencesourceid', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='morphologymethod',
            name='morphologymethod',
            field=models.CharField(max_length=45, verbose_name='Morphologymethod', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizationname',
            field=models.CharField(max_length=45, verbose_name='Organizationname', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizationshortname',
            field=models.CharField(unique=True, max_length=6, verbose_name='Organizationshortname', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='orgtype',
            name='orgtype',
            field=models.CharField(max_length=45, verbose_name='Orgtype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='passagemethod',
            name='passagemethod',
            field=models.CharField(max_length=45, verbose_name='Passagemethod', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.IntegerField(null=True, verbose_name='Organization', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='personfirstname',
            field=models.CharField(max_length=45, verbose_name='Personfirstname', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='personlastname',
            field=models.CharField(max_length=20, verbose_name='Personlastname', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='phenotype',
            field=models.CharField(max_length=45, verbose_name='Phenotype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='postcode',
            name='district',
            field=models.CharField(max_length=20, verbose_name='District'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='postcode',
            name='postcode',
            field=models.CharField(max_length=45, verbose_name='Postcode', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='primarycelldevelopmentalstage',
            name='primarycelldevelopmentalstage',
            field=models.CharField(max_length=20, verbose_name='Primarycelldevelopmentalstage', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proteinsource',
            name='proteinsource',
            field=models.CharField(max_length=45, verbose_name='Proteinsource', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher',
            field=models.CharField(max_length=45, verbose_name='Publisher', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reprogrammingmethod1',
            name='reprogrammingmethod1',
            field=models.CharField(max_length=45, verbose_name='Reprogrammingmethod1', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reprogrammingmethod2',
            name='reprogrammingmethod2',
            field=models.CharField(max_length=45, verbose_name='Reprogrammingmethod2', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reprogrammingmethod3',
            name='reprogrammingmethod3',
            field=models.CharField(max_length=45, verbose_name='Reprogrammingmethod3', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='strfplocus',
            name='strfplocus',
            field=models.CharField(max_length=45, verbose_name='Strfplocus', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='surfacecoating',
            name='surfacecoating',
            field=models.CharField(max_length=45, verbose_name='Surfacecoating', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tissuesource',
            name='tissuesource',
            field=models.CharField(max_length=45, verbose_name='Tissuesource', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transposon',
            name='transposon',
            field=models.CharField(max_length=45, verbose_name='Transposon', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='units',
            name='units',
            field=models.CharField(max_length=10, verbose_name='Units', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=45, verbose_name='Username', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraccounttype',
            name='useraccounttype',
            field=models.CharField(max_length=15, verbose_name='Useraccounttype'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='vector',
            name='vector',
            field=models.CharField(max_length=20, verbose_name='Vector', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='vectorfreereprogramfactor',
            name='referenceid',
            field=models.CharField(max_length=45, verbose_name='Referenceid', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='vectorfreereprogramfactor',
            name='vectorfreereprogramfactor',
            field=models.CharField(max_length=15, verbose_name='Vectorfreereprogramfactor', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='vectortype',
            name='vectortype',
            field=models.CharField(max_length=15, verbose_name='Vectortype', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='virus',
            name='virus',
            field=models.CharField(max_length=45, verbose_name='Virus', blank=True),
            preserve_default=True,
        ),
    ]
