# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celllines', '0076_celllinecharacterizationdifferentiationpotency_celllinecharacterizationdifferentiationpotencycelltyp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celllinedifferentiationpotency',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='celllinedifferentiationpotency',
            name='germ_layer',
        ),
        migrations.RemoveField(
            model_name='celllinedifferentiationpotencymarker',
            name='cell_line_differentiation_potency',
        ),
        migrations.RemoveField(
            model_name='celllinedifferentiationpotencymarker',
            name='morphology_method',
        ),
        migrations.RemoveField(
            model_name='celllinedifferentiationpotencymolecule',
            name='cell_line_differentiation_potency_marker',
        ),
        migrations.RemoveField(
            model_name='celllinedifferentiationpotencymolecule',
            name='molecule',
        ),
        migrations.RemoveField(
            model_name='celllinemarker',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='celllinemarker',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='celllinemarker',
            name='morphology_method',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerexpressionprofile',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerexpressionprofilemolecule',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerfacs',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerfacsmolecule',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerimune',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerimunemolecule',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkermorphology',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerrtpcr',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='undifferentiatedmorphologymarkerrtpcrmolecule',
            name='marker',
        ),
        migrations.DeleteModel(
            name='CellLineDifferentiationPotency',
        ),
        migrations.DeleteModel(
            name='CellLineDifferentiationPotencyMarker',
        ),
        migrations.DeleteModel(
            name='CellLineDifferentiationPotencyMolecule',
        ),
        migrations.DeleteModel(
            name='CellLineMarker',
        ),
        migrations.DeleteModel(
            name='Germlayer',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='Morphologymethod',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerExpressionProfile',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerExpressionProfileMolecule',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerFacs',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerFacsMolecule',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerImune',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerImuneMolecule',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerMorphology',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerRtPcr',
        ),
        migrations.DeleteModel(
            name='UndifferentiatedMorphologyMarkerRtPcrMolecule',
        ),
    ]
