FROM python:2.7

ENV http_proxy "$http_proxy"
ENV https_proxy "$https_proxy"
ENV no_proxy "$no_proxy"

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY ./ebisc /app/ebisc
COPY ./manage.py /app/
COPY ./etc/bin/run-uwsgi ./etc/bin/run-deploy ./etc/bin/run-ims-update /usr/local/bin/
ARG ROLE=production
RUN ln -s /app/ebisc/settings/${ROLE}.py /app/ebisc/settings/__init__.py \
  && mkdir -p /app/var/media /app/var/static \
  && chown -R 1001 /app \
  && chmod 775 /usr/local/bin/run-uwsgi /usr/local/bin/run-deploy /usr/local/bin/run-ims-update

COPY etc/conf/uwsgi.ini /etc/uwsgi.ini
EXPOSE 3031 9191
USER 1001
CMD ["run-uwsgi"]
