FROM nginx:stable

ARG PORT=8080

COPY ./etc/conf/nginx.conf /etc/nginx/nginx.conf

RUN sed -i -e "s/8080/$PORT/" /etc/nginx/nginx.conf

RUN chmod g+w /var/cache/nginx /run /var/log/nginx

EXPOSE $PORT

USER 1001
